export default {
  id: 'autocomplete',
  type: 'autocomplete',
  kind: '',
  mode: '',
  visibility: true,
  title: 'Title',
  isFloatingTitle: true,
  readonly: false,
  styles: [],
  activeStyles: [],
  disabledStyles: [],
  error: null,
  returnKeyType: '',
  isLoading: false,
  data: [],
  value: null,
  isSuggestionsOpened: false
  // catchRef: () => {},
  // onFocusAction: () => {},
  // onBlurAction: () => {},
  // onSubmitAction: () => {},
  // onSelectFunc: () => {},
  // onChangeFunc: () => {}
}
